import type { Metadata } from "next";

import "./globals.css";
import ThemeRegistry from "./theme-registry";

import localFont from "next/font/local";
const geistSans = localFont({
  src: "./fonts/Geist-Variable.ttf",   // 或你的实际文件名
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMono-Variable.ttf",
  variable: "--font-geist-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
